Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
