require:
  - rubocop-performance
  - rubocop-rspec

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

RSpec/NestedGroups:
  Max: 4
RSpec/DescribeClass:
  Exclude:
    - spec/readme_spec.rb

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
