require:
  - rubocop-performance
  - rubocop-rspec

Layout/IndentationStyle:
  EnforcedStyle: tabs
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

RSpec/NestedGroups:
  Max: 4
RSpec/DescribeClass:
  Exclude:
    - spec/readme_spec.rb

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
